[project]
name = "dagster-vibe-coding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster>=1.10.9",
    "webserver>=0.10.3",
]
